<a href="https://colab.research.google.com/github/herlindaaa/regresi/blob/main/multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
dataset = pd.read_csv('tourism_dataset.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[106.8271528 4.6 15 'Jakarta']
 [106.8171245 4.6 90 'Jakarta']
 [106.8335377 4.6 360 'Jakarta']
 [106.8951559 4.5 60 'Jakarta']
 [106.839134 4.5 60 'Jakarta']
 [106.8579951 4.5 10 'Jakarta']
 [106.8201865 4.5 60 'Jakarta']
 [106.8363249 4.0 60 'Jakarta']
 [103.931398 4.4 60 'Jakarta']
 [106.5237907 4.5 60 'Jakarta']
 [106.746944 4.6 60 'Jakarta']
 [106.5863989 4.0 60 'Jakarta']
 [106.6136577 4.2 60 'Jakarta']
 [106.5885 4.8 60 'Jakarta']
 [106.8417666 4.4 90 'Jakarta']
 [106.8106169 4.3 60 'Jakarta']
 [106.8130661 4.4 60 'Jakarta']
 [106.813005 4.7 60 'Jakarta']
 [106.8097144 4.6 300 'Jakarta']
 [106.8189695 4.5 90 'Jakarta']
 [106.8124452 4.5 150 'Jakarta']
 [106.83139 4.7 60 'Jakarta']
 [106.833063 4.8 60 'Jakarta']
 [106.8215901 4.6 60 'Jakarta']
 [106.8119312 4.0 45 'Jakarta']
 [106.8140791 4.3 20 'Jakarta']
 [106.842963 4.5 180 'Jakarta']
 [106.9062371 4.5 60 'Jakarta']
 [106.8265261 5.0 60 'Jakarta']
 [106.8293106 4.5 60 'Jakarta']
 [106.735584 4.3 60 'Jakarta']
 [106.8238889 4.

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
print(X)

[[1.0 0.0 106.8271528 4.6 15]
 [1.0 0.0 106.8171245 4.6 90]
 [1.0 0.0 106.8335377 4.6 360]
 [1.0 0.0 106.8951559 4.5 60]
 [1.0 0.0 106.839134 4.5 60]
 [1.0 0.0 106.8579951 4.5 10]
 [1.0 0.0 106.8201865 4.5 60]
 [1.0 0.0 106.8363249 4.0 60]
 [1.0 0.0 103.931398 4.4 60]
 [1.0 0.0 106.5237907 4.5 60]
 [1.0 0.0 106.746944 4.6 60]
 [1.0 0.0 106.5863989 4.0 60]
 [1.0 0.0 106.6136577 4.2 60]
 [1.0 0.0 106.5885 4.8 60]
 [1.0 0.0 106.8417666 4.4 90]
 [1.0 0.0 106.8106169 4.3 60]
 [1.0 0.0 106.8130661 4.4 60]
 [1.0 0.0 106.813005 4.7 60]
 [1.0 0.0 106.8097144 4.6 300]
 [1.0 0.0 106.8189695 4.5 90]
 [1.0 0.0 106.8124452 4.5 150]
 [1.0 0.0 106.83139 4.7 60]
 [1.0 0.0 106.833063 4.8 60]
 [1.0 0.0 106.8215901 4.6 60]
 [1.0 0.0 106.8119312 4.0 45]
 [1.0 0.0 106.8140791 4.3 20]
 [1.0 0.0 106.842963 4.5 180]
 [1.0 0.0 106.9062371 4.5 60]
 [1.0 0.0 106.8265261 5.0 60]
 [1.0 0.0 106.8293106 4.5 60]
 [1.0 0.0 106.735584 4.3 60]
 [1.0 0.0 106.8238889 4.4 60]
 [1.0 0.0 106.8326228 4.6 60]
 [1.0 0.0 106.7890

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [11]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [12]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[ 47985.   115000.  ]
 [ 40227.62  20000.  ]
 [ 84045.22 270000.  ]
 [ 25516.43  25000.  ]
 [ 31031.08  20000.  ]
 [  2741.95  60000.  ]
 [ 32857.43   5000.  ]
 [ 33234.88      0.  ]
 [ 24351.8       0.  ]
 [-19616.43      0.  ]
 [ 22762.07      0.  ]
 [ -4835.54      0.  ]
 [ 13466.87      0.  ]
 [ 55978.87 900000.  ]
 [ 49485.9  180000.  ]
 [ 53462.24  25000.  ]
 [  7687.75      0.  ]
 [ 51010.62      0.  ]
 [ 37597.91      0.  ]
 [601868.23 175000.  ]]
